name: Setup Rust and Prisma
description: Setup Rust and Prisma
inputs:
  targets:
    description: Comma-separated list of target triples to install for this toolchain
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Rust
      id: toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.targets }}
        toolchain: stable
        components: clippy, rustfmt

    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ inputs.targets }}
        prefix-key: "v0"
        shared-key: rust-deps
        cache-targets: ${{ runner.os != 'Windows' }}

    - name: Restore cached Prisma codegen
      id: cache-prisma-restore
      uses: actions/cache/restore@v3
      with:
        key: prisma-1-${{ runner.os }}-${{ hashFiles('./src-tauri/prisma/*', './src-tauri/Cargo.toml') }}
        path: ./src-tarui/src/db.rs

    - name: Generate Prisma client
      working-directory: src-tauri
      if: ${{ steps.cache-prisma-restore.outputs.cache-hit != 'true' }}
      shell: bash
      run: cargo prisma generate

    - name: Save Prisma codegen
      id: cache-prisma-save
      if: ${{ inputs.save-cache == 'true' }}
      uses: actions/cache/save@v3
      with:
        key: ${{ steps.cache-prisma-restore.outputs.cache-primary-key }}
        path: ./src-tarui/src/db.rs
