name: Setup Rust and Prisma
description: Setup Rust and Prisma
inputs:
  targets:
    description: Comma-separated list of target triples to install for this toolchain
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Rust
      id: toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.targets }}
        toolchain: stable
        components: clippy, rustfmt

    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ inputs.targets }}
        prefix-key: "v0"
        shared-key: rust-deps
        workspaces: "src-tauri -> ./target"
        cache-targets: ${{ runner.os != 'Windows' }}
